[package]
name = "horsenuggets/luauproject-cli"
description = "A CLI tool for instantiating new Luau projects."
version = "1.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/horsenuggets/luauproject-cli"
realm = "shared"
include = [
    "default.project.json",
    "init.luau",
    "LICENSE",
    "README.md",
    "Source",
    "Source/**",
    "wally.toml",
]
exclude = ["**"]
private = true

[dependencies]
Chalk = "horsenuggets/chalk-luau@1.0.2"
Commandline = "horsenuggets/commandline-luau@0.2.3"

[dev-dependencies]
Testable = "horsenuggets/testable@1.1.4"
